# Header

menu:
  主页: /
  归档: /archives/index.html
  分类: /categories

# Site
title: Strive-Man
subtitle: To Be Yourself,Never Stop Fighting！
description: Come on Man
keywords:
author: Strive-Man
language: en
timezone: ''

# SubNav
subnav:
  github: "https://github.com/strive-man"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://account.bilibili.com/account/home?spm_id_from=333.999.0.0"
  #acfun: "#"
  mail: "mailto:gqzhang166@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link:  
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 是否开启分类的标签
category_tag: true
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
#reward_type: 2
# 打赏wording
#reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
#alipay: 
# 微信二维码图片地址
#weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '此篇文章无目录(T_T)…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favio.jpg

#你的头像url
avatar: /me.jpg
# 头像是否旋转
avatarrotation: true
#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: 'cywTK3OgE'
changyan_conf: '71bb32bec5af7ae1429e187c89cb6b13'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  #header: '#00000'
  header: 'linear-gradient(55deg,#333333,#00B1D2,#F3F3F3,#FFD100)'
  # 右滑板块背景
  #slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'
  #slider: 'linear-gradient(55deg,#88ACDB,#49B1F5,#9534f1,#49b1f5)'
  #slider: 'linear-gradient(55deg,#00B1D2,#00B1D2,#F3F3F3,#00B1D2,#00B1D2)'
  slider: 'linear-gradient(#00B1D2,#00B1D2,#c7ecee,#00B1D2,#00B1D2)'
  #slider: 'linear-gradient(#FFFFFF,#F5F5F5,#E0E0E0,#00B1D2)'
  
    
#主色调：#333333（黑色）
#辅助色1：#00B1D2（蓝色）
#辅助色2：#F3F3F3（灰色）
#强调色：#FFD100（黄色）
  
  
# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '联系我'
friends:
  CPP101: https://ccp101.com/

aboutme: How Many Roads Must a Man Walk Down，</br>Before You Call Him a Man！</br></br>持续奋斗，做硬汉！</br></br>微信号：16611651802

